@baseUrl = http://localhost:3333

###
# Create User
POST {{baseUrl}}/cadastrar
Content-Type: application/json

{
    "name": "joseph",
    "email": "opa@gamil.com",
    "senha": "zezinho"
}

###
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "joseph@gamil.com",
    "senha": "zezinho"
}

###
@token = {{login.response.body.acessToken}}

#List Schedules
###
GET {{baseUrl}}/schedules/free
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/schedules/free/day/12:00
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/schedules/free/hour/2025-08-20
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/schedules/hairDresser/hour/2025-05-27/1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/schedules/hairDresser/day/12:00/2
Authorization: Bearer {{token}}

#List Services
###
GET {{baseUrl}}/schedules/type
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/schedules/hairDresser
Authorization: Bearer {{token}}

#Create Schedule
###
POST {{baseUrl}}/schedule
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "destinary_name": "joseph",
    "destinary_email": "joseph@gamil.com",
    "dayHorarioId": "8b0ab28a-e068-493e-967d-d3f5983e4794",
    "tipoServicoId": "1",
    "cabeleleiroId": "1"
}