# Create User
POST http://localhost:3333/cadastrar
Content-Type: application/json

{
    "name": "joseph",
    "email": "joseph@gamil.com",
    "senha": "zezinho"
}

###
POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "joseph@gamil.com",
    "senha": "zezinho"
}

#List Schedules
###
GET http://localhost:3333/schedules/free
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

###
GET http://localhost:3333/schedules/free/day/12:00
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

###
GET http://localhost:3333/schedules/free/hour/2025-05-28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

###
GET http://localhost:3333/schedules/hairDresser/hour/2025-05-27/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

###
GET http://localhost:3333/schedules/hairDresser/day/12:00/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

#List Services
###
GET http://localhost:3333/schedules/type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

###
GET http://localhost:3333/schedules/hairDresser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg

#Create Schedule
###
POST http://localhost:3333/schedule
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWZiYjQxNi03NWVmLTQwNWMtOWNmMi04YzJlZTMwOWM2MDUiLCJpYXQiOjE3NDgzNTY0MzksImV4cCI6MTc0ODM2MzYzOX0.EWRNuC0oiTRq_RZhtEbVpnuy60jenu6WUT9QhAxeeFg
Content-Type: application/json

{
    "destinary_name": "joseph",
    "destinary_email": "joseph@gamil.com",
    "dayHorarioId": "8b0ab28a-e068-493e-967d-d3f5983e4794",
    "tipoServicoId": "1",
    "cabeleleiroId": "1"
}